language: php

dist: precise

php:
  - 7.2

before_script:
  - '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && composer config -g disable-tls true || true'
  - '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && composer config -g secure-http false || true'
  - composer install

script: "php artisan test"

branches:
  except:
    - setup
