<?php

class Add_Dummy_Revisions {

	/**
	 * Make changes to the database.
	 *
	 * @return void
	 */
	public function up()
	{

		Session::start('cookie');
		DB::query('DELETE from subjects');
		DB::query('DELETE from subjects_revisions');

		$query = <<<SQL

INSERT INTO `subjects` (`id`, `title`, `slug`, `factbox`, `summary`, `year`, `created_by`, `created_at`, `updated_at`)
VALUES
	(1,'Accounting and Finance','accounting-and-finance','Accounting and Finance at Kent was ranked 11th in the UK for overall student satisfaction in the National Student Survey 2011.','Accountants are probably best known for checking the validity of company accounts-auditing- but they also devise and operate financial systems, conduct investment analysis, advise on business start-ups, company takeovers and company rescue schemes, and handle individuals\' and corporations\' tax affairs.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(2,'Accounting and Management','accounting-and-management','Kent was ranked 5th in the UK for Business and Management graduate employment prospects in The Guardian University Guide 2012.','At Kent Business School, we have designed the Accounting and Management degree to ensure that it responds to the needs and expectations of the modern accountancy and management professions. This programme equips you with knowledge, understanding and skills relevant to a career in accounting or management as well as for professional training in accounting.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(3,'Accounting &amp; Finance','accounting-finance','Kent was ranked 6th in the UK for Business and Management graduate employment prospects in The Guardian University Guide 2011 and 3rd for student satisfaction in The Sunday Times University Guide 2011.','Accountants are probably best known for checking the validity of company accounts ? auditing ? but they also devise and operate financial systems, conduct investment analysis, advise on business start-ups, company takeovers and company rescue schemes, and handle individuals\' and corporations\' tax affairs.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(4,'Actuarial Science','actuarial-science','Kent was ranked 1st in the UK for Mathematics graduate employment prospects and 8th for student satisfaction in The Complete University Guide 2012.','Actuaries evaluate and manage financial risks, particularly in the financial services industry. They form a small yet well-respected, influential and relatively well-paid profession. If you are good at mathematics and you are curious about financial matters, you should enjoy studying actuarial science.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(5,'American Studies','american-studies','American Studies at Kent was ranked 3rd in the UK for student satisfaction in the National Student Survey 2011.','American Studies dates back to 1973 at the University of Kent. The programme is taught by an impressive range of internationally recognised scholars who specialise in American film, literature, history and politics. Students are encouraged to visit the United States or Latin America through our exchange system.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(6,'Ancient History','ancient-history','Kent was ranked 4th in the UK for Archaeology in the 2011 National Student Survey, with 97% of students saying they were satisfied with the quality of their course.','The great strength of Ancient History is that it allows you to specialise in the study of the ancient civilisations of Egypt, Persia, Greece and Rome that lie at the very heart of European culture and the cultures that border the Mediterranean.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(7,'Anthropology','anthropology','Kent was ranked 6th in the UK for Anthropology graduate employment prospects in The Guardian University Guide 2012 and 8th for student satisfaction in TheTimes Good University Guide 2012.','Anthropology addresses the big question - what makes us human? It is the study of human beings: how we evolved, why we live in different sorts of societies around the world, and how we interact with one another and the environment. An exciting and varied subject, anthropology covers a huge number of topics including human evolution, primatology, genetics, reproduction, nutrition, religion, kinship, politics and development.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(8,'Architecture','architecture','85% of our undergraduate students found graduate level employment within six months of graduating.','One of the most important roles of architectural intervention is to enhance the quality of life of those whom it touches. We deal in the invention of new, hitherto unimagined environments, the resuscitation of existing buildings and urban settlements, and the careful enhancement of our towns, cities, rural environments and landscapes to provoke surprise, delight and wonder.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(9,'Art and Film','art-and-film','Kent was ranked 4th in the UK for Art and Design graduate employment prospects in The Guardian University Guide 2012 and The Complete University Guide 2012.','Art and Film offers a unique opportunity to combine art history and film studies in a single honours degree. It cuts across the boundaries of different visual media, exploring perspective, colour and light, movement, montage and the portrayal of painting, photography, drawings, prints and sculpture in film and video.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(10,'Astronomy, Space Science and Astrophysics','astronomy-space-science-and-astrophysics','Physics and Astronomy at Kent was ranked 1st in the UK for overall student satisfaction in The Times Good University Guide 2012.','Kent runs a fantastic programme for students who are inspired by the wonders and vastness of the universe. In this course, there are opportunities to investigate the possibilities of life elsewhere in the universe. You get involved with real space missions from ESA and NASA, and can work on Hubble Telescope data and images from giant telescopes.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(11,'Autism Studies','autism-studies','One in 100 people have an autism spectrum condition.','The Autism Act and the Autism Strategy produced by the Department of Health highlight the need for appropriate training for those who work with people on the autism spectrum.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(12,'Biochemistry','biochemistry','Biochemistry at Kent was ranked 9th in the UK for student satisfaction in the National Student Survey 2011.','Biochemistry deals with the way living organisms function at the molecular level. This covers a vast variety of life forms, ranging from comparatively simple viruses and bacteria to mammals like ourselves. Biochemistry will have a major impact on many of the problems that face mankind today, particularly in the areas of medicine, agriculture and the environment.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(13,'Biological Anthropology','biological-anthropology','Kent was ranked 6th in the UK for Anthropology graduate employment prospects in The Guardian University Guide 2012 and 8th for student satisfaction in TheTimes Good University Guide 2012.','Biological anthropology focuses on the study of human evolution and adaptation. Biological anthropologists are particularly interested in investigating why variation arose and how it is maintained, as well as trying to explain how people are adapted to the environments in which they live. They study the human fossil and stone tool record, primate behaviour, human material culture and the development of modern human behaviour in evolutionary and comparative perspective. Typical questions that interest biological anthropologists could be: why do people have different skin colours or facial shapes? Does the environment affect fertility? What are the best ways to assess childhood malnutrition? When and how did humans evolve? What does chimpanzee aggression say about human violence? How much can you really tell about a person from their skeleton? Why is sex fun?','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(14,'Biology','biology','The School of Biosciences at Kent was ranked 8th in the UK for employability by The Guardian University Guide 2012.','Biology influences our everyday lives, and is at the forefront of social change, for example, in human cloning, stem-cell research, genetically-modified organisms, the human genome project, humanity\'s effect on the environment, and the potential risks of some foods. It investigates, describes and analyses the structures and functions of living organisms and their interactions with the environment.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(15,'Biomedical Science','biomedical-science','Biomedical Science at Kent was ranked 11th in the UK for Overall Student Satisfaction in the 2011 National Student Survey.','Are you interested in a career in the health services, in a pharmaceutical company or in medical research? Would you like to explore the biochemical processes that occur in the human body, and particularly diseases like cancer or the response to infection? Are you intrigued to learn how medicines are discovered and how they work?','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(16,'Business Administration','business-administration','Kent was ranked 5th in the UK for Business and Management graduate employment prospects in The Guardian University Guide 2012.','Management and business are in the top ten subjects for degree course choices as they combine excellent academic training with good career prospects. The Bachelor of Business Administration (BBA) degree gives you the academic foundation you need for a career in business or management.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(17,'Business and Managment','business-and-managment','Kent was ranked 4th in the UK for Business Studies in The Complete University Guide 2012 and 5th for Business and Management graduate prospects in The Guardian University\nGuide 2012.','Business and management is regularly one of the top ten most popular degree subjects, as it combines excellent academic training with good career prospects. Studying business at the University of Kent at Medway gives you an understanding of the modern world of business that will greatly enhance your opportunities for employment. The programme includes a year in industry.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(18,'Business (top-up)','business-top-up','','The University of Kent\'s top-up programme offers you the chance to attain an honours degree after one full academic year of university study, once you have gained an HND or foundation degree with a compatible syllabus in Business or other business-related discipline.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(19,'Classical and Archaeological Studies','classical-and-archaeological-studies','Kent was ranked 4th in the UK for Archaeology in the 2011 National Student Survey, with 97% of students saying they were satisfied with the quality of their course.','The great strength of Classical and Archaeological Studies is the hugely interesting and varied range of subjects it includes ? literature, mythology, drama, archaeology, art and architecture, history, languages and philosophy ? and the way they all connect in the study of ancient civilisations, including those of Egypt, Greece and the Roman Empire.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(20,'Comparative Literature','comparative-literature','Comparative Literature at Kent was ranked 1st in the UK for overall student satisfaction in the National Student Survey 2011.','Our modules in Comparative Literature cover literature from the classics to the modern age. We investigate literary movements such as Romanticism, Realism, Modernism and Postmodernism, and also how and why literary forms have evolved in different cultures and linguistic traditions. For example: what makes a tragedy by Sophocles so different from one written by Shakespeare? How has the genre of science fiction developed across Europe? What are the similarities and differences between a novel by Jane Austen and one by Goethe? Why has the tale survived as a literary form from ancient times to the present day?','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(21,'Computer Science','computer-science','Two of our computing students who graduated in 2009 are earning £50,000 per year working for investment banks.','Computer Science is an exciting and rapidly developing subject that offers excellent employment prospects and well-paid careers.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(22,'Computer Systems Engineering','computer-systems-engineering','In the 2010 National Student Survey, Kent was ranked 1st among UK higher education institutions for the quality of Electronic and Electrical Engineering courses.','The range of uses for computers is increasing all the time - from smart phones and games consoles to aircraft flight control systems, super computers and global telecommunications.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(23,'Computing - Joint Honours','computing---joint-honours','Computer Science was ranked 7th in the UK for graduate employment prospects in The Sunday Times University Guide 2012.','Graduates who can offer employers a thorough understanding of the application of computing to business situations, in addition to expertise in another specialism, are in great demand.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(24,'Conservation','conservation','Over 75% of DICE graduates are in paid employment or postgraduate study within six months of completing their degree. Nearly 60% of DICE graduates stay in the environmental sector.','The Durrell Institute of Conservation and Ecology (DICE) in the School of Anthropology and Conservation at Kent is a leading international research and training centre dedicated to the conservation of biodiversity and ecosystems around the world. DICE was founded in 1989 with a clear mission: to break down the barriers between the natural and social sciences in order to inform progressive approaches to conservation. Thats why we are in a School that also includes anthropology. One component of DICE\'s work is to train a new, interdisciplinary generation of conservationists who think innovatively about the challenges that lie ahead. As undergraduates, you are part of a dynamic and growing community of conservationists whose work spans all major regions of the world.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(25,'Creative Events: Design and Production','creative-events-design-and-production','Kent was ranked 4th in the UK for graduate employment for Art and Design students in The Guardian University Guide 2012 and The Complete University Guide 2012.','This unique degree introduces you to creative, practical and organisational approaches to devising a range of exciting live events from street performances to product launches; from installations to community celebrations. The programme helps you to find ways of making extraordinary acts of imagination come to life.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(26,'Criminal Justice Studies','criminal-justice-studies','Kent was ranked 7th in the UK for Social Policy and Administration graduate employment prospects in The Guardian University Guide 2012.','Criminal Justice Studies looks at the key elements of contemporary crime policy: policing, the courts, punishment and prevention. The programme modules address many contemporary issues in criminal justice, including: poverty, hate crime, illegal drug use, restorative justice, the care of victims, community safety, domestic violence, political responses to crime, anti-social behaviour, penal policy, social justice and human rights.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(27,'Criminology','criminology','Kent was ranked 7th in the UK for Social Policy and Administration graduate employment prospects in The Guardian University Guide 2011.','Crime and criminal justice are major social and political issues. Why do people commit crime? How much crime is committed? What causes crime rates to rise or fall? How should we deal with offenders? How can crime be effectively prevented?','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(28,'Cultural Studies','cultural-studies','Kent\'s Gulbenkian Arts Centre is a major regional arts cinema and also hosts top comedy acts and leading theatre productions as well as staging student shows.','What do we mean by culture and why are its many forms so hotly contested today? Why is it so important to our sense of identity and belonging? How are the culture wars of today, surrounding such things as free speech, drugs, food, censorship, secrecy, piracy and youth culture related to uses of old and new media and the rise of global capitalism? Do you think it matters how tradition and heritage are represented in the mass media or in museums? Do you think popular culture is much more than a form of entertainment Do you ever think that the culture and lifestyle which means a lot to you is not taken seriously? It is often said that the world is changing more rapidly than at any other time in history, and the study of cultural transformation is key to achieving the ?joined-up thinking\' society needs in the 21st century.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(29,'Design: Design for Performance','design-design-for-performance','Kent was ranked 6th in the UK for Art and Design in The Times Good University Guide 2010.','This degree is specifically focused on design for theatrical performance, either within theatres or in converted or found spaces. You are introduced to design for a range of work, from classical theatre to post modern site-specific performance, from dance to drama.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(30,'Design: Event and Experience Design','design-event-and-experience-design','Kent was ranked 2nd in the UK for graduate employment for Art and Design students in The Guardian University Guide 2011.','This unique degree introduces you to creative, practical, and managerial approaches to devising a range of exciting live events from street performances to product launches; from installations to community celebrations. The programme helps you to find ways of making extraordinary acts of imagination come to life.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(31,'Digital Arts','digital-arts','We have a Digital Media Hub, where you can work with leading lights in the creative industries.','Digital technology has had a tremendous impact on all forms of communication in the 21st century. Using computers, visual artists can manipulate all forms of artefacts whether video, photographic images, sound clips or text to create exciting new experiences for audiences.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(32,'Drama and Theatre Studies','drama-and-theatre-studies','In the National Student Survey 2011, 93% of Kent Drama and Theatre Studies students were satisfied with the quality of the teaching on their course.','As a Kent Drama and Theatre Studies student, you can choose between a three-year BA (Hons) programme, our unique four-year MDrama degree and a range of joint honours options. We also offer you the opportunity to spend a year abroad or a year in industry.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(33,'Drama and Theatre','drama-and-theatre','In the National Student Survey 2011, 93% of Kent Drama and Theatre students were satisfied with the quality of the teaching on their course.','As a Kent Drama and Theatre student, you can choose between a three-year BA (Hons) programme, our unique four-year MDrama degree and a range of joint honours options. We also offer you the opportunity to spend a year abroad or a year in industry.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(34,'Economics','economics','Economics at Kent was ranked 3rd in the UK for teaching excellence in The Sunday Times University Guide 2012 and 5th in the UK for overall student satisfaction in the National Student Survey 2011.','Economics examines some of the profound issues in our life and times, including: economic growth and sustainable development, emerging market economies, financial and monetary crises, environmental and natural resource problems, international trade and aid to poor countries. When you study at Kent, you have the chance to learn about these issues from economists who are highly regarded within the profession for emphasising the practical application of economics in all of these arenas.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(35,'Electronic and Communications Engineering','electronic-and-communications-engineering','Electrical and Electronic Engineering at Kent was ranked 1st for overall student satisfaction in the 2012 editions of The Complete University Guide, The Guardian University Guide and The Times Good University Guide.','Electronics-based products play a vital role in our daily lives, from the sophisticated diagnostic equipment used in modern hospitals to leading-edge fibre optic communications. Computer technology, telecommunications and consumer electronics are advancing at an ever-increasing pace.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(36,'English Language and Linguistics','english-language-and-linguistics','English Language and Linguistics at Kent was ranked 2nd in the UK in the 2011 National Student Survey.','Studying English Language and Linguistics provides an opportunity to discover and explore a dynamic and often controversial field which is crucial to our understanding of spoken and written language in all their complexity. English Language and Linguistics at Kent is a broad and exciting programme which allows you to tailor your studies to suit your individual interests and possible career paths. You will be studying the most varied and rapidly changing language in the world ? a large and all-encompassing subject.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(37,'English Literature','english-literature','In the National Student Survey 2011, 92% of English Studies students were satisfied with the quality of their course.','English at Kent is challenging, flexible, and wide-ranging. It covers both only traditional areas (such as Shakespeare or Dickens) and newer fields such as American literature, creative writing, postcolonial literature and recent developments in literary theory. We also offer the opportunity for you to spend a year studying abroad in either America or Europe.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(38,'Environmental Studies','environmental-studies','Over 75% of DICE graduates are in paid employment or postgraduate study within six months of completing their degree. Nearly 60% of DICE graduates stay in the environmental sector.','The Durrell Institute of Conservation and Ecology (DICE) in the School of Anthropology and Conservation at Kent is a leading international research and training centre dedicated to the conservation of biodiversity and ecosystems around the world. DICE was founded in 1989 with a clear mission: to break down the barriers between the natural and social sciences in order to inform progressive approaches to conservation. That\'s why we are in a School that also includes anthropology. One component of DICE\'s work is to train a new, interdisciplinary generation of conservationists who think innovatively about the challenges that lie ahead. As undergraduates, you are part of a dynamic and growing community of conservationists whose work spans all major regions of the world.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(39,'European Studies','european-studies','In the National Student Survey 2011, European Languages and Area Studies at Kent was ranked 15th in the UK for student satisfaction, with 92% of students satisfied with the quality of their course.','European Studies at Kent gives you the opportunity to study the politics, history and culture of Europe in the nearest UK city to continental Europe. We call ourselves the UK\'s European university, not only because of our proximity to the continent but also because of our extensive network of connections and partnerships in Europe.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(40,'Film Studies','film-studies','Cinematics and Photography at Kent is ranked 4th in the UK for overall student satisfaction in the National Student Survey 2011.','For over 30 years, the University of Kent has been at the forefront of developing film studies as an academic subject. We are one of the three major universities in the UK for film studies, and one of the most highly regarded departments in Europe.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(41,'Film','film','Cinematics and Photography at Kent is ranked 4th in the UK for overall student satisfaction in the National Student Survey 2011.','For over 30 years, the University of Kent has been at the forefront of developing film studies as an academic subject. We are one of the three major universities in the UK for film studies, and one of the most highly regarded departments in Europe.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(42,'Fine Art','fine-art','Kent was ranked 8th in the UK for Art and Design in The Complete University Guide 2012.','Our Fine Art programme offers you the option of working with many different media and arts practices. This may include painting, sculpture, installation, critical writing and curation, to name a few examples.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(43,'Forensic Sciences','forensic-sciences','Kent was ranked 1st in the UK for Forensic and Archaeological Science graduate employment prospects.','Forensic science is a high-profile subject in the UK. It has received a lot of new investment for expansion since the well-publicised miscarriages of justice in the 1970s. As a result, scientific liaison officers have been appointed by the police service and the knowledge and communication gap between the scientists and the police at a crime scene has narrowed. Forensic skills are used in a wide range of professions and industries; for instance, at disaster scenes, within archaeology and in the food and pharmaceutical industries.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(44,'French','french','French at Kent was rated 7th nationally in the most recent Research Assessment Exercise (RAE).','Canterbury is the closest British university city to mainland Europe, and our proximity to the Channel ports and Ashford International station means you can be in France in just a couple of hours. There are also many French speaking students on campus, so you get a better chance to immerse yourself in the language than at any other university in the country. In the most recent Research Assessment Exercise (RAE), French at Kent came 7th in the UK, which means that during your studies at Kent you will be working with top-rated researchers.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(45,'German','german','German at Kent was ranked 4th in the UK for graduate employment prospects in The Complete University Guide 2012.','Both culturally and commercially, German is an extremely important language. Within Europe, it is spoken by more people than English or French. Worldwide, it is the third most widely used language on the internet, (after English and Japanese), and it is frequently used as a second language in Eastern Europe, where it serves as a means of communication across international boundaries. Fluency in the German language, combined with knowledge of the political and cultural development of the German-speaking world, opens up career opportunities in many parts of the continent. At Kent, we specialise in teaching the language, literature and culture of the German-speaking world of today, and exploring its literary and social history.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(46,'Health and Social Care','health-and-social-care','In the most recent Research Assessment Exercise, 70% of research in the School of Social Policy, Sociology and Social Research was judged ?world leading\' or ?internationally excellent\'.','Studying Health and Social Care offers both a stimulating course of study and a route into a large and growing number of careers. Health and social care present numerous challenges within society today as expectations rise, new technologies become available and debates flourish as to how care should be provided and paid for. Should ?cloning\' or ?assisted suicide\' be permitted? Should fertility treatment be available as a right on the NHS? Should older people pay for their own care? Are services delivered fairly to all sections of the community? You will have the opportunity to consider these and many other questions relating to these important topics.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(47,'Hispanic Studies','hispanic-studies','Kent was ranked 3rd in the UK for Iberian Languages graduate employment prospects and 4th for student satisfaction in The Complete University Guide 2012.','Spanish is one of the most widely spoken languages in the world - outside Spain it is the official language of all countries in South and Central America except Brazil, and is widespread in many parts of North America. The programme at Kent gives you the opportunity to explore the languages and cultures of Spain and Spanish America while developing your language skills. You can study Hispanic Studies at Kent whether you have an A level or GCSE in Spanish, or whether you are a beginner.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(48,'History and Philosophy of Art','history-and-philosophy-of-art','Kent was ranked 4th in the UK for graduate employment prospects for art and design students in The Guardian University Guide 2012.','For over 20 years, Kent has been at the cutting edge in providing innovative and interdisciplinary teaching approaches in the visual arts. We have established research strengths in aesthetics, contemporary art, photographic studies, the philosophy of art, art history and in developing teaching approaches to the subject. These interests are reflected in the rich variety of modules we offer our students throughout their time at Kent.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(49,'History','history','History at Kent was rated 2nd nationally in the most recent Research Assessment Exercise.','Any study of history engages a natural human curiosity about the past. History is an exciting and diverse subject, which is reflected in the flexibility and breadth of the BA in History offered at Kent.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(50,'Information Technology','information-technology','Students who choose the Year in Industry option and gain real work experience typically get a higher degree result at graduation.','The Information Technology (IT) degrees give you the skills you need for the practical application of computing to areas typically found in industry. These include e-commerce, information systems, and computer consultancy. The Business Information Technology degree incorporates much of the IT course, but also includes business oriented modules.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(51,'Intellectual and Developmental Disabilities degree','intellectual-and-developmental-disabilities-degree','Social Policy at Kent was ranked 10th in the UK for overall student satisfaction in the National Student Survey 2011.','Recent scandals in the provision of services to people with intellectual and developmental disabilities have drawn attention to the importance of specialist staff training. This programme, taught at the Tizard Centre - a leading centre for teaching, research and service provision in intellectual/ developmental disabilities and autistic spectrum disorders - offers such training. It is designed specifically for those who provide community and school-based services, such as home leaders, peripatetic team leaders, instructors, community support staff, special educational needs teachers and teaching assistants.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(52,'Intellectual and Developmental Disabilities Foundation','intellectual-and-developmental-disabilities-foundation','','This programme, enables you to work in constructive, non-aversive and ethically sound ways with people who are often marginalised and vulnerable, and to develop the practical skills essential for effective working in this area.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(53,'Intellectual and Developmental Disabilities','intellectual-and-developmental-disabilities','Social Policy at Kent was ranked 10th in the UK for overall student satisfaction in the National Student Survey 2011.','Recent scandals in the provision of services to people with intellectual and developmental disabilities have drawn attention to the importance of specialist staff training. This programme, taught at the Tizard Centre - a leading centre for teaching, research and service provision in intellectual/ developmental disabilities and autistic spectrum disorders - offers such training. It is designed specifically for those who provide community and school-based services, such as home leaders, peripatetic team leaders, instructors, community support staff, special educational needs teachers and teaching assistants.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(54,'International Business','international-business','Kent was placed 6th in the UK for Business and Management graduate employment prospects in The Guardian University Guide 2012.','This programme offers you the opportunity to pursue a thorough grounding in general business subjects while developing more detailed knowledge and skills within the specialism of international business.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(55,'International Foundation Programme','international-foundation-programme','The International Foundation Programme at Kent is one of the most well-established and well-respected courses of its type in the UK.','If you need to extend your existing academic qualifications, study skills or ability in English for direct entry to university, the University of Kent\'s one year International Foundation Programme gives you the opportunity to do so.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(56,'Italian','italian','In the 2011 National Student Survey 92% of European Languages and Area Studies\' students were satisfied with the overall quality of their course.','With Italy continually proving herself as a cornerstone in culture, art and history across Europe, you cannot help but be inspired to learn the language. By learning Italian, you give yourself a tool to explore this cultural richness and to open your eyes to its Roman heritage, the Renaissance, modern architecture, fashion and car design. It is a hugely popular language spoken not only in its home country, but also by over 15 million people in Switzerland, North America and Australia.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(57,'Journalism','journalism','Students on the BA in Journalism and the News Industry are eligible to compete for the Sky News Bob Friend Memorial Scholarship. For details go to www.centreforjournalism.co.uk','Journalism is fascinating, rewarding and influential. In a world hungry for information about issues ranging from global warming to fashion and from armed conflict to football, the ultra-competitive modern media market needs versatile, multimedia journalists with cutting-edge academic and vocational skills and a highly developed awareness of ethics.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(58,'Law at Canterbury','law-at-canterbury','Kent Law School was the winner of the Attorney General\'s Award 2011 for Best Contribution by a Law School (to Pro Bono work), for the work of the Kent Law Clinic.','Kent Law School is recognised as one of the leading law schools in the UK. It has an international reputation both for its research and for the high quality, innovative, critical and socio-legal education that it provides. It boasts a carefully designed and wide-ranging curriculum, an institutional commitment to teaching excellence, as well as extensive international links. In addition to offering a highly successful mooting programme and a variety of activities to prepare students for successful future careers, the Law School also houses a multi-award winning Law Clinic that offers students the opportunity to gain unparalleled experience of legal practice, enabling them to advise and represent clients under the supervision of qualified solicitors.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(59,'Law at Medway','law-at-medway','Kent Law School was the winner of the Attorney General\'s Award 2011 for Best Contribution by a Law School (to Pro Bono work), for the work of the Kent Law Clinic.','The Certificate in Law is an innovative one-year programme (equivalent to Stage 1 of the LLB) which offers a supportive and inclusive environment for students who do not yet meet Kent Law School\'s normal entry requirements but who demonstrate ability and potential, and who would benefit from a more supportive study environment to aid their transition to higher education.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(60,'Liberal Arts','liberal-arts','The University of Kent was ranked 23rd in the UK for teaching excellence in The Guardian University Guide 2012.','Kent\'s Liberal Arts programme teaches you to see the world from a range of perspectives ? political, cultural, historical and economic ? and to develop your understanding of how each impacts on the other. You learn to unpick the causes of crises, whether financial, cultural or political, and are encouraged to be creative in developing alternative approaches to the challenges facing societies around the world.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(61,'Mathematics and Statistics','mathematics-and-statistics','Kent was ranked 1st in the UK for Mathematics graduate employment prospects and 8th for student satisfaction in The Times Good University Guide 2012.','Mathematics is important to the modern world. All quantitative science, including both physical and social sciences, is based on it. It provides the theoretical framework for physical science, statistics and data analysis as well as computer science. Our programmes reflect this diversity and the excitement generated by new discoveries within mathematics that affect not only the technicalities of science but also our general understanding of the world in which we live.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(62,'Medical Anthropology','medical-anthropology','Kent was ranked 6th in the UK for Anthropology graduate employment prospects in The Guardian University Guide 2012 and 8th in the UK for student satisfaction in The Times Good University Guide 2012.','Why do people get sick? Are humans the only species that use medicine? How do medical systems evolve? What happens when folk medicine and professional biomedicine are used at the same time? What are the health effects of mass-produced food? What makes plants effective medicines?','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(63,'Multimedia Technology and Design','multimedia-technology-and-design','We have a Digital Media Hub, where you can work with leading lights in the creative industries.','In current technology, communications, computing and entertainment have converged to create completely new media possibilities and experiences. These creative industries need people who can combine digital technology skills with creative ability to meet design challenges.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(64,'Music - all options','music---all-options','','','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(65,'Music Technology','music-technology','The Department of Music and Audio Arts is part of the new School of Arts at Medway, a stunning multimillion-pound development housing a range of music and arts-based programmes.','Our BSc (Hons) Music Technology degree strikes a balance between the technical and the creative aspects of music technology. You develop your technical skills in sound recording, audio processing, editing and mixing, while also gaining important knowledge of the underlying scientific principles. Your creative side is encouraged through musical tasks such as composition, arrangement and remixing.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(66,'Music','music','We have brand new performance spaces and music studios, containing excellent, industry-standard equipment.','Our BMus Music offers you the opportunity to develop your skills, knowledge and advanced understanding of the subject needed by today\'s musicians. You study a wide range of music, looking at earlier, historical styles as well as music that has evolved over the past few decades. Your technical skills in performance and music notation are an important feature of this degree, and we also encourage you to find your own creative voice with specialist composition modules.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(67,'Pharmacy','pharmacy','Kent was ranked 1st in the UK for Pharmacology and Pharmacy graduate prospects in the 2012 editions of The Guardian University Guide, The Sunday Times Good University Guide, The Times Good University Guide and The Complete University Guide.','Medway School of Pharmacy is a unique partnership between the University of Kent and University of Greenwich. The School has achieved full accreditation by the General Pharmaceutical Council and is recognised as an established School of Pharmacy.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(68,'Philosophy','philosophy','Philosophy was ranked 7th in the UK for graduate employment prospects in The Guardian University Guide 2012.','What is philosophy? Why is it important? Is it relevant? As a student of Philosophy at Kent, you do not so much learn about philosophy as learn to do it yourself. This includes not only studying major philosophies and philosophers, but also contributing your own ideas to an ongoing dialogue. You develop the ability to connect the most abstract ideas to the most concrete things in our experience.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(69,'Physics','physics','Physics and Astronomy at Kent was ranked 1st in the UK for overall student satisfaction in The Times Good University Guide 2012.','Physics reaches from the quark out to the largest of galaxies, and encompasses all the matter and timescales within these extremes. At the heart of a professional physicist is a fascination with the ?how and why\' of the material world around us. We aim to equip you with the skills to understand these phenomena and to qualify you for a range of career pathways.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(70,'Politics and International Relations','politics-and-international-relations','In the National Student Survey 2011, 95% of Kent Politics students were satisfied with the overall quality of their course, ranking the School 7th in the UK for overall student satisfaction.','Politics and international relations is an exciting, fast-changing, broad-based discipline.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(71,'Popular Music','popular-music','The Department of Music and Audio is part of the new School of Arts at Medway, a stunning multi-million pound development housing a range of music and arts-based programmes.','Our BMus Popular Music gives you the opportunity to study the many forms of popular music at the new School of Arts development in the Chatham Historic Dockyard. This inspirational, waterside setting contains refurbished historic buildings, specialist music facilities and performances spaces.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(72,'Primary Dental Care','primary-dental-care','In the National Student Survey 2010 in Subjects Allied to Medicine, 93% of Kent\'s students were satisfied with the quality of their course.','Future dental provision requires the best and most appropriate use of targeted professional skills, as well as effective regulation, all delivered through the concept of fully integrated and devolved team working. As part of the Centre for Professional Practice, the Division of Dentistry is dedicated to the provision of lifelong learning for the entire dental team to encourage skill-mix and to enhance clinical and non-clinical competencies.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(73,'Psychology','psychology','The School was ranked 4th in the UK for overall student satisfaction in The Guardian University Guide 2012.','Psychology is the study of people: how they think, act, react and interact. Psychologists scientifically study all kinds of behaviour and the thoughts, feelings and motivations underlying behaviour. Psychology examines questions such as: how do people act on a first date? How can we ease the effects of parental divorce on children? How can we make teams work efficiently? How can we help people to overcome depression or phobias? By collecting information about what people do, think, perceive and feel, psychologists answer questions about human behaviour, cognition and development.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(74,'Religious Studies','religious-studies','Religious Studies at Kent was ranked 4th in the UK for overall student satisfaction in The Complete University Guide 2012.','Religion is a vital element in human culture, and today religious issues are everywhere ? from current affairs and international events, to the history of ideas, art and literature, and our own immediate experience and environment. Religious Studies at Kent involves investigating and discussing these ideas, experiences, practices and institutions, through texts, films, historical data and directly observing the world today.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(75,'Social Anthropology','social-anthropology','Kent was ranked 6th in the UK for Anthropology graduate employment prospects in The Guardian University Guide 2012 and 8th for student satisfaction in The Times Good University Guide 2012.','The BA in Social Anthropology is a distinctive degree programme allowing for the holistic study of people\'s ideas, beliefs, practices and activities in a wide range of local, global, diasporic and transnational settings. Social anthropologists study how and why we do the things we do, for example, how we work, use technologies, and negotiate conflicts, relationships and change.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(76,'Social Policy','social-policy','Kent was ranked 7th in the UK for Social Policy graduate employment prospects in The Guardian University Guide 2012.','Social Policy looks at the ways in which we as a society promote the welfare of individuals and families. You study some of today\'s central issues, such as poverty, well-being, ill health, education, crime, homelessness and child protection. This includes looking at both the nature of social problems and also at the policies directed towards them by government, and at the role of voluntary and private welfare. You look at debates regarding how best to provide health care, how to provide affordable housing, how to balance work and family life, and how to achieve equality for women, minority ethnic groups and people with disabilities. In studying these and many other vital topics, you develop the knowledge and skills to help you succeed in your future career.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(77,'Social Sciences','social-sciences','Kent was ranked 7th in the UK for Social Policy graduate employment prospects in The Guardian University Guide 2012.','Social Sciences offers an interdisciplinary approach to investigating society and people by providing an opportunity to study different subjects (social policy, sociology, criminology, history, politics, psychology and urban studies). Social issues, including class, forensic psychology, urban change, health care, social justice, cultural identity, crime, work, the city, and drugs, are never simple to understand, but this degree programme provides a multi-perspective analysis of such issues. In addition, new and returning students value the ability to select topics and modules to match their interests and needs in a flexible and coherent manner. You can choose from an expanding list of new modules taught by a dedicated research-active staff.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(78,'Social Work','social-work','Kent was ranked 4th in the UK for Social Work in The Times Good University Guide 2012.','The degree in Social Work offers successful graduates eligibility for professional registration with the General Social Care Council (GSCC) and with the Health and Care Professions Council (HCPC), which, from July 2012, will be the regulatory body for social work. The degree provides the national required standard in knowledge and skills needed by professional social workers. The programme also provides extensive work in practice learning settings that meet Government requirements.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(79,'Sociology','sociology','Kent was ranked 7th in the UK for Social Policy graduate employment prospects in The Guardian University Guide 2012.','Sociology provides ways of making sense of a world undergoing unprecedented social change and uncertainty. It aims to explain the origins, formation and development of modern societies. Sociological research is devoted to understanding the conditions that govern our experience of everyday life as well as the structures that determine the overall character of a society.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(80,'Sport and Exercise for Health','sport-and-exercise-for-health','Students at the Centre for Sports Studies use a range of state-of-the-art equipment and take part in sports therapy clinics, all of which gives them the relevant experience they need for success in their future careers.','Sport and Exercise for Health is a new degree programme offered by the Centre for Sports Studies. This BSc (Hons) degree is designed for students who wish to combine their passion for sport and exercise with the desire for health-related study. In this science-based programme, you develop a range of laboratory and clinical skills that give you an outstanding platform for a career in the sport, exercise and health professions.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(81,'Sport and Exercise Management','sport-and-exercise-management','The Centre for Sports Studies has new facilities in Medway Park as part of an £11 million project creating a regional centre of sporting excellence.','Studying Sport and Exercise Management in the Centre for Sports Studies, you develop an excellent understanding of the management expertise needed to be effective in the sport and exercise industry. The course provides an excellent grounding both in sport and exercise, and management skills. In your third year, you have the opportunity to complete a placement module within the sports industry and also choose to focus on personal training, corrective exercise, and/or strength and conditioning.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(82,'Sports Science','sports-science','Kent was ranked 9th in the UK for Sports Science graduate employment prospects in The Complete University Guide 2012.','This stimulating degree programme enables you to study the application of science to issues in the sport and exercise sciences, and to gain the key skills you need to become an excellent practitioner within the sports, exercise and fitness industries. You are taught by lecturers who are world-leading experts in their field and who are involved in some of the latest sport and exercise science research developments. This means that the knowledge you gain is relevant and up-to-date.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(83,'Sports Therapy','sports-therapy','Our Sports Therapy students gain hands-on experience at many top sporting events such as the London Marathon, the Modern Pentathlon World Cup in Medway and the London Triathlon.','This leading, externally accredited BSc (Hons) degree programme in Sports Therapy is for motivated students with a strong interest in this fast-growing profession. The Centre for Sports Studies provides a first-rate experience for its students in an innovative environment, with enthusiastic and supportive staff. You are taught by leading researchers and practitioners in their field and learn to diagnose, treat and prevent sporting injuries. In addition to honing your clinical skills, you learn how to exercise, train and rehabilitate people, ranging from young competitors to ageing adults, including elite athletes and those with chronic disease. Graduates from this degree may be eligible for voluntary registration with the Health Professions Council in the future.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(84,'Visual and Performed Arts','visual-and-performed-arts','Kent was ranked 4th in the UK for Art and Design students graduate employment and received a score of 9/10 for ?value added\' in The Guardian University Guide 2012.','Visual and Performed Arts (VPA) is a multidisciplinary programme which is unique to Kent. It is run by departments with an international reputation for academic excellence and subject innovation.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(85,'War Studies','war-studies','History at Kent was rated 2nd nationally in the 2008 Research Assessment Exercise.','What makes countries, ethnic groups or individuals go to war? How has warfare changed with the introduction of new technology? How has propaganda been used? Can we learn anything from history?','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00'),
	(86,'Web Computing','web-computing','The School of Computing is in the top 20 in the UK for graduate prospects in The Guardian Good University Guide 2011.','The incredible growth of the web over the last decade has had a major impact on business and commerce.','2013','mb324','2012-05-08 15:32:23','0000-00-00 00:00:00');


SQL;

		DB::query($query);

		// Easiest way to do this is save every one of these again, thus creating the first revision.

		$subjects = Subject::all();

		foreach ($subjects as $subject) {
			// Time stamp to make it dirty.
			$subject->created_by= 'mb324';

			$subject->save();
		}

	}

	/**
	 * Revert the changes to the database.
	 *
	 * @return void
	 */
	public function down()
	{
		DB::query('DELETE from subjects');
		DB::query('DELETE from subjects_revisions');
	}

}